### ISSUE TITLE
Is it possible to get a legacy version for OS X 10.7?

### ISSUE THREAD

**Issue by eteb3** [Bilalh/Tagger#51]
Forgive me if this is a noob question - and please delete if so:

I have 10.7 and would like to run Tagger. Is there a legacy version available? If I try to run Tagger I get a system message saying I need 10.8.

Thank you.

**Comment by Bilalh** [comment]
**I will not support this old version in anyway**  but this worked when I was using 10.7 https://github.com/downloads/Bilalh/Tagger/Tagger_1.6.2.zip

**Comment by eteb3** [comment]
Thank you, much appreciated.
