### ISSUE TITLE
Does NOT work with 10.7.5

### ISSUE THREAD

**Issue by Murphy1976** [Bilalh/Tagger#57]
The requirements stated that this was tested on 10.8, and "should" work on 10.7 .
It does not.

**Comment by Bilalh** [comment]
I forgot to update website, the correct information is on the github page https://github.com/Bilalh/Tagger namely 

`Only tested on the latest Mac OS X 10.10 release, should work on 10.9`   

You could try an older version from https://github.com/Bilalh/Tagger/releases which might work with 10.7
